[project]
name = "demo-simpy-textual"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pytest-watcher>=0.4.3",
    "simpy>=4.1.1",
    "textual>=2.1.2",
    "textual-dev>=1.7.0",
    "textual-plotext>=1.0.1",
]
